# https://github.com/yildizozan/tenserflow-lambda/blob/2c29535b9af0a396ca13e53aada10e46b0579791/.github/workflows/deploy.yml
# https://github.com/destination-unknown/destination-unknown-backend-serverless/blob/master/.github/workflows/main.yml
# https://github.com/search?utf8=%E2%9C%93&q=extension%3Ayml+path%3A.github%2Fworkflows%2F+serverless+python&type=Code&ref=advsearch&l=&l=

name: Verify and autodeploy to staging environment

on:
  push:
    branches:
      - deploy-alb-external
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv

      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 13

      - name: Install Serverless Framework and other
        run: |
          npm install -g

      - name: Deploy Lambda function to dev
        run: |
          PATH="$PATH:/home/runner/.local/bin"
          which serverless
          which sls
          echo $PATH
          # serverless deploy --stage dev --force --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
